replicaCount: 1
image:
  repository: peishu/checkoutservice
  tag: 25831ea348285ce9728fbe32496bd4c5245579ef
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 5050
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
